---
- name: Install GlusterFS packages
  hosts: gluster_nodes
  become: yes
  become_method: sudo
  gather_facts: yes
  collections:
    - ansible.builtin
  tasks:
    - name: Ensure GlusterFS packages are installed
      ansible.builtin.package:
        name:
          - glusterfs
          - glusterfs-server
          - glusterfs-client
          - glusterfs-fuse
        state: present

    - name: Ensure required support packages are installed
      ansible.builtin.package:
        name:
          - lvm2
          - xfsprogs
        state: present

    - name: Enable and start Gluster daemon
      ansible.builtin.service:
        name: glusterd
        state: started
        enabled: true
