---
- name: Remove Gluster peer gracefully
  hosts: gluster_nodes
  become: true
  collections:
    - ansible.builtin
    - gluster.gluster
  vars:
    primary_node: "{{ groups['gluster_nodes'][0] }}"
  pre_tasks:
    - name: Require peer_to_remove variable
      ansible.builtin.assert:
        that:
          - peer_to_remove is defined
          - peer_to_remove in groups['gluster_nodes']
          - groups['gluster_nodes'] | length > 1
        fail_msg: "Set peer_to_remove to a member of the gluster_nodes group that is not the only node."

  tasks:
    - name: Prepare final brick layout without departing peer
      ansible.builtin.set_fact:
        remaining_bricks: "{{ groups['gluster_nodes'] | difference([peer_to_remove]) | product(gluster_bricks) | map('join', ':') | list }}"
      run_once: true
      delegate_to: "{{ primary_node }}"
      delegate_facts: true

    - name: Shrink volume while migrating data
      gluster.gluster.gluster_volume:
        state: present
        name: "{{ gluster_volume_name }}"
        bricks: "{{ hostvars[primary_node].remaining_bricks }}"
        rebalance: true
      run_once: true
      delegate_to: "{{ primary_node }}"

    - name: Ensure brick removal is committed
      gluster.gluster.gluster_volume:
        state: started
        name: "{{ gluster_volume_name }}"
      run_once: true
      delegate_to: "{{ primary_node }}"

    - name: Detach departing peer
      gluster.gluster.gluster_peer:
        state: absent
        nodes:
          - "{{ peer_to_remove }}"
      run_once: true
      delegate_to: "{{ primary_node }}"
